MongoDB: switch to only MongoDB 3.6+ & pymongo 3.7+
pymongo.errors.ConfigurationError: Server at localhost:27017 reports wire version 4, but this version of PyMongo requires at least 6 (MongoDB 3.6).